export const ORDER_TABLE_COLUMNS = [
    {
        key: 'orderStage',
        header: 'Stage',
        width: 'w-[120px] md:w-[180px]',
        align: 'center',
        responsive: 'always-visible',
    },
    {
        key: 'order',
        header: 'Order ID',
        width: 'w-[120px]',
        align: 'center',
        responsive: 'md-visible',
    },
    {
        key: 'customer',
        header: 'Customer',
        width: 'w-[180px]',
        align: 'center',
        responsive: 'md-visible',
    },
    {
        key: 'email',
        header: 'Email',
        width: 'w-[120px]',
        align: 'center',
        responsive: 'md-visible',
    },
    {
        key: 'bill',
        header: 'Total',
        width: 'w-[150px] md:w-[250px]',
        align: 'center',
        responsive: 'always-visible',
    },
    {
        key: 'dateOrder',
        header: 'Date',
        width: 'w-[120px]',
        align: 'center',
        responsive: 'md-visible',
    },
    {
        key: 'payMethod',
        header: 'Pay Method',
        width: 'w-[120px]',
        align: 'center',
        responsive: 'md-visible',
    },
    {
        key: 'payStatus',
        header: 'Pay Status',
        width: 'w-[120px]',
        align: 'center',
        responsive: 'always-visible',
    },
    {
        key: 'details',
        header: 'Details',
        width: 'w-[120px]',
        align: 'right',
        responsive: 'always-visible',
    },
];
